Make profile inheritance explicit
ResearchObject/ro-crate pull request #262
Opened 2023-05-23 01:43 UTC by stain

In some cases, such as [Workflow Run Crate](https://www.researchobject.org/workflow-run-crate/profiles/) there are multiple profiles that are related with inheritance.

There are also less strict inheritance profiles such as https://trefx.uk/trusted-wfrun-crate/0.3/

This section clarifies that when conforming to multiple profiles they should all be listed under `conformsTo`. It also declares how a Profile Crate can list other profiles.

2023-05-24 10:16 UTC, simleo requested changes

2023-07-27 20:33 UTC, ptsefton commented
Didn't we decide to remove all this from 1.2? @stain

2023-09-28 21:39 UTC, ptsefton commented
This needs to be moved to a different document, right?

2024-02-08 08:41 UTC, stain commented
Remove inheritance, at best "referenced/suggested" profiles.

2024-04-11 08:51 UTC, stain commented
Decision 2024-04-11: Not do formal inheritance system at RO-Crate level yet before we have tried out how it works with actual implementations (e.g. SHACL, Crate-O modes) -- then facilitate them.

2024-04-26 00:15 UTC, stain commented on docs/1.2-DRAFT/profiles.md
> +    "hasArtifact": {"@id": "https://w3id.org/ro/wfrun/process/0.1"}
I've modified this example to be complete of workflow/0.1 that then references both process/0.1 and workflow RO-Crate

2024-04-26 00:20 UTC, stain commented on docs/1.2-DRAFT/profiles.md
> +
Yes, (finally) added such a recommendation:

> In the conforming crate, any terms defined in the profile using `DefinedTerm`, `rdfs:Class` and `rdf:Property` must be either be used as full URIs matching the `@id`, or mapped to these URIs from the conforming crate's JSON-LD `@context`. Note that JSON-LD only expands keys from `@id` and `@type`.

2024-04-26 00:25 UTC, stain commented
I have finally managed to tidy up the profile section.

Changes:
- Merged to latest master (but pending #296 with retrieval section moved out from here)
- Use only `rdfs:Class` and `rdf:Property`, documented as _Schema.org style schemas_
- Inheritance across profiles now only "Multiple Profiles" as suggestions of conformance only
- Renamed section "Shared contextual entities from a Profile Crate"
- Examples expanded following @simleo's suggestion

2024-04-26 00:36 UTC, stain commented
Suggestion in call 2024-04-25 @CaroleGoble was to also look at Delegation pattern:

- https://en.wikipedia.org/wiki/Delegation_pattern
- https://refactoring.guru/replace-delegation-with-inheritance
- https://stackoverflow.com/questions/832536/when-to-use-delegation-instead-of-inheritance
- https://www.jetbrains.com/help/idea/replace-inheritance-with-delegation.html

In a sense we use delegation pattern in https://trefx.uk/5s-crate/0.4/#referencing-a-workflow-crate as instead of subclassing Workflow RO-Crate, it references the Workflow RO-Crate by URL -- one crate to another.   I've documented this pattern in #296.

This would make the resulting 5s-crate as Workflow Run Crate not conform to any strict inheritance rules, as it would not have the usual `ComputationalWorkflow` etc. and so should not itself declare `conformsTo` the Workflow RO-Crate  (which we would have to then make Workflow RO-Crate indirection also be a workflow language!).  

Note a side issue: at the moment that 5s-crate is in that case purposefully ignoring the MUST of [conformsTo requirements](https://www.researchobject.org/workflow-run-crate/profiles/0.4/workflow_run_crate#requirements) -- we can argue over that separately!

2024-05-20 19:10 UTC, stain commented on docs/1.2-DRAFT/profiles.md
>  }
Added

2024-05-20 19:11 UTC, stain commented
@simleo Good to go..?

2024-05-21 15:24 UTC, simleo approved these changes

2024-05-21 15:24 UTC, simleo commented
> @simleo Good to go..?

AFAICT, yes

2024-05-23 20:01 UTC, merged